Calculate texture scale and offset for brushes.
bonjorno7/SourceOps pull request #80
Opened 2022-04-23 20:54 UTC by Nieblist

Map face vertex UVs to VMF UV axes for brushes. Add an "Allow Skewed Textures" option in the map export panel to keep non-perpendicular UV axes intact, otherwise it will modify the V axis to make them orthogonal.

2022-04-23 21:00 UTC, Nieblist commented
Hi reviewers. **Please note that the Allow Skewed Textures option is not working for all cases right now.** It seems to be flipping some textures or otherwise having some issues.

I decided it keep it because it can be useful (I'm using it for my map), but if you prefer I can remove it for now and create another PR in case I find a way to fix it.

2022-05-07 15:15 UTC, Nieblist commented
Hi @bonjorno7, please let me know if there is any reason not to merge this. It has been pretty useful for my map. Do you prefer me to remove the "Allow Skewed Textures" option and keep only orthogonal mappings?

2022-05-07 18:41 UTC, bonjorno7 commented
Hi @Nieblist sorry for the wait, I've been ~~busy~~ lazy.
I'll take a thorough look in the coming days, and merge if all is well.

2022-05-07 18:56 UTC, bonjorno7 requested changes
I think you've done an amazing job, and I only have a few small nitpicks and questions.

2022-05-07 18:56 UTC, bonjorno7 commented on addon/ops/export_vmf.py
> +        )
Kind of a nitpick, but I'd prefer a trailing comma here, so each item gets its own line.

2022-05-07 18:56 UTC, bonjorno7 commented on addon/props/map_props.py
> +        default=1.0,
Seems slightly out of scope, but I'm fine with it.

2022-05-07 18:56 UTC, bonjorno7 commented on addon/types/map_export/brush.py
> +    if face.material_index < len(obj.material_slots):
Might want to use `face.material_index in range(len(obj.material_slots))`  to make sure that negative numbers don't cause any trouble; though I'm not sure if those can happen so it probably doesn't matter.

2022-05-07 18:56 UTC, bonjorno7 commented on addon/types/map_export/brush.py
> +                    texture_side_length = mat_node.image.size[0]
I'm curious why the width and not the height, but you don't have to explain if you don't feel like it.

2022-05-07 18:56 UTC, bonjorno7 commented on addon/types/map_export/brush.py
> +    return texture_side_length
Perhaps it makes sense to do an early return instead of a break, then return the default value at the bottom; saves you 2 lines of code (44 & 52).

2022-05-07 18:56 UTC, bonjorno7 commented on addon/types/map_export/brush.py
> +            v_vals.append(1 - uv[1])
Would this have been necessary with my old code too, or is it required because of something in your math?
Just curious; doesn't really matter.

2022-05-07 18:56 UTC, bonjorno7 commented on addon/types/map_export/brush.py
> +    v_axis = f'[{bitangent[0]} {bitangent[1]} {bitangent[2]} {v_offset}] {v_scale * settings.texture_scale}'
I'm not even going to pretend to understand any of this fancy math stuff, but good job!

2022-05-07 18:56 UTC, bonjorno7 commented on addon/types/map_export/vmf.py
> +    ):
I'd like a trailing comma here as well.

2022-05-07 18:56 UTC, bonjorno7 commented on addon/types/map_export/brush.py
> +    v_axis = f'[{bitangent[0]} {bitangent[1]} {bitangent[2]} {v_offset}] {v_scale * settings.texture_scale}'
Right yeah this isn't an issue so I'll resolve it.

2022-05-07 18:57 UTC, bonjorno7 commented
Oh and I'm fine with keeping the skewed textures option, even if it isn't perfect (the rest of the addon isn't either).

2022-05-10 19:58 UTC, Nieblist commented
Cool! I updated it, please let me know if there is something else (#79)

2022-05-23 22:18 UTC, Nieblist commented
Hi @bonjorno7! Sorry to bug you.,I'm Just pinging you again in case we can merge this :)

2022-05-23 22:42 UTC, bonjorno7 commented
Oh sorry I forgot, will take a look and maybe merge tomorrow.

2022-06-04 11:35 UTC, bonjorno7 commented
Sorry for being so unavailable, I should be better.
Everything looks good now, and seems to work fine from my testing, so I'll merge.
Thank you for your contribution!

2022-06-04 11:35 UTC, merged

2022-08-13 15:39 UTC, Nieblist commented
Happy to help, thank you for the plugin!